-- AlterTable
ALTER TABLE `OrganizationMember` MODIFY `role` ENUM('SUPER_ADMIN', 'TEACHER', 'STUDENT') NOT NULL;

-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('SUPER_ADMIN', 'TEACHER', 'STUDENT') NOT NULL;
